baseURL = "https://bprzybylski.github.io/IB-CS-GeS/"
title = "IB Computer Science @ Gaudium et Studium"
theme = "hugo-book"
copyright = "Bart≈Çomiej Przybylski"
enableGitInfo = true

[markup]
  defaultMarkdownHandler = "goldmark"
    [markup.goldmark.renderer]
    unsafe = true

[params]
  BookToC = false
  BookSection = '*'
  BookSearch = false
  BookComments = false
  BookRepo = 'https://github.com/bprzybylski/IB-CS-GeS'
